# Variables
EXE=des

#Special rules and targets
.PHONY: all build check clean help

#Rules and targets

all: build

build: 
	@cd src && $(MAKE)
	@cp -f src/$(EXE) .

clean:
	@cd src && $(MAKE) clean
	@rm -f $(EXE)

help :
	@echo -e "Usage :"
	@echo -e "  make [all]		build"
	@echo -e "  make build		build the software"
	@echo -e "  make clean		remove all files generated by make"
	@echo -e "  make help		display this help"
